---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the htpdate_package variable
  set_fact:
    htpdate_package: "{{ __htpdate_package }}"
  when: htpdate_package is not defined

- name: Set the htpdate_env_file variable
  set_fact:
    htpdate_env_file: "{{ __htpdate_env_file }}"
  when: htpdate_env_file is not defined

- name: Set the htpdate_daemon variable
  set_fact:
    htpdate_daemon: "{{ __htpdate_daemon }}"
  when: htpdate_daemon is not defined

- name: Ensure htpdate package is installed
  package:
    name: "{{ htpdate_package }}"
    state: present

- name: Populate service facts
  service_facts:

- name: Disable systemd-timesyncd if it's running but htpdate is enabled
  service:
    name: systemd-timesyncd.service
    enabled: false
    state: stopped
  when:
    - htpdate_enabled | bool
    - '"systemd-timesyncd.service" in services'

- name: Ensure htpdate is running and enabled as configured
  service:
    name: "{{ htpdate_daemon }}"
    enabled: true
    state: started
  when: htpdate_enabled | bool

- name: Ensure htpdate is stopped and disabled as configured
  service:
    name: "{{ htpdate_daemon }}"
    enabled: false
    state: stopped
  when: not (htpdate_enabled | bool)

- name: Configure htpdate environment file
  template:
    src: "{{ htpdate_env_file | basename }}.j2"
    dest: "{{ htpdate_env_file }}"
    mode: 0644
  notify: restart htpdate
  when: htpdate_manage_env | bool
